name: Multiple compilers and versions

on:
  push:

jobs:
  my_matrix:
    name: Compiler test
    strategy:
      fail-fast: false
      matrix:
        CC: [
          gcc-9,
          g++-9,
          gcc-10,
          g++-10,
          gcc-11,
          g++-11,
          gcc-12,
          g++-12,
          gcc-13,
          g++-13,
          gcc-14,
          g++-14,
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        env:
            CC: ${{ matrix.CC }}
        run: ./autogen.sh && ./configure && make && make dist
